name: kostebekvurma
description: "A new Flutter project."
publish_to: 'none' # Remove this line if you wish to publish to pub.dev

version: 1.0.0+1

environment:
  sdk: ^3.7.2

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.8
  audioplayers: ^5.2.1
  shared_preferences: ^2.2.2
  flutter_animate: ^4.3.0
  lottie: ^2.7.0
  flame: ^1.14.0
  provider: ^6.1.1

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0

flutter:
  uses-material-design: true
  
  assets:
    - assets/images/
    - assets/audio/
  
  fonts:
    - family: GameFont
      fonts:
        - asset: assets/fonts/JungleAdventurer.ttf
        - asset: assets/fonts/JungleAdventurer.otf
